### PR TITLE
Lint me

### PR DESCRIPTION
**Pull request by mrhut10**
just a effort to clean up code-base according to the lint rules you had turned on.

careful, i have disabled all linting within the tailwind config file.

hopefully i haven't broken anything else in the process

### CODE REVIEW

**Comment by mrhut10** [comment]
this was the work that was stuck on my dead laptop from i believe Wednesday night.

glad it merged locally without conflicts :)

**Comment by mrhut10** [comment]
apparently i shouldn't have used "git revert" in this case, as git cherry-pick command would have been more applicable 
slug's oh well

**Comment by mrhut10** [comment]
Im hoping I haven't broken anything here @lukebennett88 

Walking though the linting errors was a good way to familiarise myself the the codebase

**Comment by lukebennett88** [comment]
This is great, thanks so much. 
I must admit I'd seen the errors about destructuring and prop validation, but didn't really know how to fix it. Makes sense now, I'll be doing this for all my other projects when I get time 👍

**Comment by mrhut10** [comment]
No problem, glad I could do something simple whist also indirectly learning the rough codebase structure.

I think most of them were just warnings not errors, however there was one error that I didn't invest in getting my head around withing the tailwind configuration file. Which is why that file has a global eslint ignore command at the beginning of it now.

Obviously there is some danger doing this, but figured as long as your aware we could resolve properly later.

You can put a eslint check as first part of your build script if you liked. Which raise a build error on a pr or build that had lint errors automatically.

**Comment by lukebennett88** [comment]
Yeah the Tailwind errors also are nothing to worry about. Just a few `require()` that go unused, I just commented them out and removed the ESLint ignore comment.
No more ESLint warnings/errors 😌

**Comment by mrhut10** [comment]
Nice, want me to add prebuild script check lint before building.

**Comment by lukebennett88** [comment]
Yeah that would be great 👍

**Pull request merged**
